# Generated by Django 4.1 on 2022-09-27 13:13

from django.db import migrations, models
import students.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(default=None, max_length=254, validators=[students.validators.valid_email_domains]),
        ),
        migrations.AlterModelTable(
            name='students',
            table='student_table',
        ),
    ]
