# Generated by Django 4.1 on 2022-10-21 14:03

from django.db import migrations, models
import students.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_create_datetime_student_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default=None, max_length=254, validators=[students.validators.ValidEmailDomain('@gmail.com', '@yahoo.com')]),
        ),
    ]
