# Generated by Django 4.1.1 on 2022-09-21 18:38

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(max_length=100)),
                ('data_start', models.DateField(default=django.utils.datetime_safe.date.today)),
                ('description', models.TextField()),
            ],
        ),
    ]
