# Generated by Django 4.1 on 2022-09-30 18:57

from django.db import migrations, models
import groups.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(max_length=100)),
                ('data_start', models.DateField(validators=[groups.validators.validate_start_date])),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Groups',
            },
        ),
    ]
