# Generated by Django 4.1 on 2022-10-23 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('name_group', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField(default=datetime.datetime.utcnow)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Groups',
                'db_table': 'groups',
            },
        ),
    ]
