# Generated by Django 4.1 on 2022-10-12 11:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='groups',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groups',
            name='headman',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headman_group', to='students.student'),
        ),
        migrations.AddField(
            model_name='groups',
            name='start_date',
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
        migrations.AddField(
            model_name='groups',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
