# Generated by Django 4.1 on 2022-10-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_groups_create_datetime_groups_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='data_start',
        ),
        migrations.AlterModelTable(
            name='groups',
            table='groups',
        ),
    ]
