# Generated by Django 4.1 on 2022-10-21 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_email'),
        ('groups', '0003_remove_groups_data_start_alter_groups_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='headman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headman_group', to='students.student'),
        ),
    ]
