# Generated by Django 4.1 on 2022-10-21 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_email'),
        ('groups', '0004_alter_groups_headman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='headman',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headman_group', to='students.student'),
        ),
    ]
